[package]
name = "vector-common"
version = "0.1.0"
authors = ["Vector Contributors <vector@datadoghq.com>"]
edition = "2021"
publish = false
license = "MPL-2.0"

[features]
default = [
  "btreemap",
  "conversion",
  "tokenize",
  "encoding",
  "sensitive_string"
]

btreemap = []

byte_size_of = []

conversion = []

encoding = [
  "btreemap"
]

sensitive_string = []

test = []

tokenize = []

sources-utils-net-tcp = []
sources-utils-net-udp = []

[dependencies]
async-stream = "0.3.6"
async-trait.workspace = true
bytes = { version = "1.9.0", default-features = false }
chrono.workspace = true
crossbeam-utils = { version = "0.8.20", default-features = false }
derivative = { version = "2.2.0", default-features = false }
flate2.workspace = true
futures.workspace = true
indexmap.workspace = true
metrics.workspace = true
paste = "1.0.15"
pin-project.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec = { version = "1", default-features = false }
stream-cancel = { version = "0.8.2", default-features = false }
tokio = { version = "1.43.0", default-features = false, features = ["macros", "time"] }
tracing = { version = "0.1.34", default-features = false }
vrl.workspace = true
vector-config = { path = "../vector-config" }
hostname = { version = "0.4.0", default-features = false }
dyn-clone.workspace = true
snafu.workspace = true
regex.workspace = true
tokio-util.workspace = true
serde_with.workspace = true
zstd.workspace = true

[dev-dependencies]
futures = { version = "0.3.31", default-features = false, features = ["async-await"] }
tokio = { version = "1.43.0", default-features = false, features = ["rt", "time"] }
tempfile = "3.15.0"
rand.workspace = true
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }
toml.workspace = true
similar-asserts = "1.6.0"
